### ISSUE TITLE
Todo - 완성 안된 부분

### ISSUE THREAD

**Issue by 0505eok** [Oh-JunYoung/CowAPI-Front#4]
## 에러처리
- [x] 400번대 에러에 대한 일괄 처리

## AI
- [x] icon 추가 및 클릭 이벤트
- [x] API 연동 및 확인

## ETC
- [x] 나가기 버튼 처리
